
import {Poppins, Raleway } from 'next/font/google'
import { getProjectsBySlug } from '@/sanity/lib/projects/getProject';

const poppins = Poppins({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-poppins',
});

const raleway = Poppins({
  subsets: ['latin'],
  weight: ['400','500', '600'],
  variable: '--font-raleway',
});

// export const metadata = {
//   title: "Tamjid Ahmed",
//   description: "Generated by create next app",
// };


export async function generateMetadata({ params }) {
  const { slug } = params;
  const result = await getProjectsBySlug(slug);


  if (!result) {
    return {
      title: "Project Not Found",
      description: "The requested project could not be found.",
    };
  }

  // Return metadata based on fetched data
  return {
    title: result.title || "Default Title",
    description:  "Default Description",
  };
}




export default async function getLayout({ children }) {
  
  return (
  <main>
      {children}
  </main>
  );
}
