import localFont from "next/font/local";
import "./globals.css";
import {Poppins, Raleway } from 'next/font/google'
import Footer from "@/components/Footer";
import { Suspense } from "react";


const poppins = Poppins({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-poppins',
});

const raleway = Poppins({
  subsets: ['latin'],
  weight: ['400','500', '600'],
  variable: '--font-raleway',
});

export const metadata = {
  title: "Tamjid Ahmed",
  description: "Generated by create next app",
};


// export async function generateMetadata({params }) {

  

//   return {
//     title: 'yy',
//     description:'test description'
//   }
// }




export default async function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${raleway.variable} antialiased bg-[#F2F5F9] `}
      >
{/* <div>
{children}

</div> */}

<Suspense fallback={<div>Loading...</div>}>
            
            {children}
        </Suspense>
     <Footer />
     
      </body>
    </html>
  );
}
