
import './globals.css'
import { Inter } from 'next/font/google'
import icon from '../../public/tamu.png'
import getMeta from '../../lib/getMetaData'

const inter = Inter({ subsets: ['latin'] })



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   icons: {
//   icon: '../../public/vercel.svg'

//   }
// }

export async function generateMetadata() {
  const result = await getMeta()
  console.log(result[0].title) 
  return {
    title: result[0].title,
    description: result[0].description,
    icons:{
      icon: '../../public/tamu.png'
    }
  }
}


export default function RootLayout({ children }) {





  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
